### ISSUE TITLE
パスがユーザ名に依存している

### ISSUE THREAD

**Issue by AkkyOrz** [inox-ee/dotfiles#12]
https://github.com/inox-ee/dotfiles/blob/43fb8c1c9f9e36a86c0bf0cdf6ea73f8f37202b4/.fzf.zsh#L3-L13

`/home/ddz92478/`を`$HOME`に置換しても良さそう

**Comment by inox-ee** [comment]
すでに修正済み (https://github.com/inox-ee/dotfiles/commit/fb21430eebff5102e0d38a458ace6a20bcde013d) のはずです
